### PR TITLE
fix missing data['error']

### PR DESCRIPTION
**Pull request by dronord**

### CODE REVIEW

**Comment by dronord** [comment]
Noah, what you think about?

**Comment by gocart** [comment]
Just curious, is this throwing an error for you? The only time the error field should be filled in is when there is an actual error.

**Comment by dronord** [comment]
$ uname -oi
x86_64 GNU/Linux

$ php --version
PHP 5.3.3 (cli) (built: Jul  3 2012 16:53:21)

test.php:
<?php
$data['id'] = '';
$data['error'] .= 'asdf';
?>

$ php test.php
PHP Notice:  Undefined index: error in /path/test.php on line 3

If $data['error'] = ''; then <?php if (!empty($error)): ?> in header.php return False. All right.

**Comment by gocart** [comment]
I'm confused by your last post.  can tell you though that the reason your snippet would return and error is because you've got .= after $data['error'] rather that just a = sign.

**Comment by dronord** [comment]
controllers/admin/categories.php:200
$data['error']  .= $this->upload->display_errors();
$data['error'] not defined before - got "PHP Notice: Undefined index....".

**Pull request merged**
