### PR TITLE
update payment view

### PR DESCRIPTION
**Pull request by briangelhaus**
update error view for payment for go cart 2.0

<div class="error" id="payment_error_box" style="display:none"></div>

to

<div class="alert alert-error" id="payment_error_box" style="display:none"></div>

### CODE REVIEW

**Comment by gocart** [comment]
ok I'm rather confused by this pull request. Why update 1.2 when the development branch is 2.0 development? When 2.0 is ready the 1.2 branch will be a legacy and 2.0 will become the primary branch.

**Comment by briangelhaus** [comment]
Ya I thought I was on on 2.0. Sorry. But hopefully you see what needs changed.

**Comment by gocart** [comment]
Hey there, just wanted to follow up. looks like that view was updated a while back already. Thanks for taking an active part in the application!

**Comment by briangelhaus** [comment]
I was editing the bootstrap theme, so i dont know how it says i edited 1.2. Bootstrap isnt even on 1.2,

But anyways, I just downloaded the lastest version from git hub and yes you did update it awhile ago, but you still missed 1.

https://github.com/gocart/GoCart/blob/2.0-Development/gocart/themes/bootstrap/views/checkout/payment_form.php

Line 14 should be the same as line 64... just needs a different error class

**Comment by ghost** [comment]
cool thanks, just updated the other line.

-Noah Mormino

**Pull request closed without merging**
