### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by verhaeghep**
I made a translation to Dutch for GoCart.  I just didn't understand the following line:
$lang['error_file_upload'] = '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.

Where can I find the error in the upload script?

### CODE REVIEW

**Comment by ghost** [comment]
This would be found in the CodeIgniter core language files.

Every CodeIgniter library uses language files. You may be able to find a Dutch translation of CodeIgniter out there on the internet already.

thanks! 

-Noah Mormino
Clear Sky Designs

**Comment by verhaeghep** [comment]
Ok, I found it. Tnx.
Last question about the translation: where is $lang['form_term'] used?  I don't understand what you mean by "Term" therefore I cannot translate it.

**Comment by ghost** [comment]
There are a BUNCH of language strings in there, can you tell me the filename and line you found that on? Then I can tell you what I was referring to.

-Noah Mormino
Clear Sky Designs

**Comment by verhaeghep** [comment]
gocart/languages/english/common_lang.php on line 47
$lang['form_term']                      = 'Term';

**Comment by ghost** [comment]
haha, well, I looked and I could not find that line used anywhere. I can only assume that it was a mistake. I'll go ahead and remove it.

-Noah Mormino
Clear Sky Designs

**Comment by ghost** [comment]
I removed that line from the development branch. If you can, please update your translation to match.

thanks!

**Comment by verhaeghep** [comment]
Translation updated and complete now.

**Comment by ghost** [comment]
Thank you so much for putting this much effort forth into a translation of GoCart. What we would like to do is rather than bundling each translation into the core package, offer any translations as additional downloads. That way, if we ever get to the point of 20 translations, we won't have that many languages bundled in the application (thus making the download considerably larger). We would be interested in setting up a repository for alternative languages.

**Comment by verhaeghep** [comment]
No problem for me.  I would suggest to put all alternative languages in 1 repository, making them available in one download.  Separate downloads for each language is not practical.
Good luck with the further development of GoCart.

**Comment by verhaeghep** [comment]
Update dutch language for the upcoming 1.2.0 release

**Pull request closed without merging**
