### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Dinesh-Ramakrishnan**
I have implemented Social Login with GoCart,
Now User can login using Yahoo or Google Account.
Soon I will integrate Facebook Login also.

### CODE REVIEW

**Comment by gocart** [comment]
Hey there Dinesh, I downloaded your copy of GoCart. I was really intrigued by the social login feature. Now that I tried it though I have some questions. I logged in with Google and I still had to register, now after I registered anyway, I was able to log in with Google. My question is what is the point of social login integration if I have to create an account anyway?

What would happen if I were to log in with google or open ID and change my password in GoCart?

By the way, thanks for being so active in GoCart I hope to find the time to test and integrate some of your pull requests.

**Comment by Dinesh-Ramakrishnan** [comment]
Hi,

Thank you for your time to test this feature.

<i>"My question is what is the point of social login integration if I have to create an account anyway?"</i>

I thought we have to create an account in GoCart so that we can manage the Address and Orders for the User.  Please correct me if I am wrong.
The Registration Form is shown to user since we have to get the User's Phone Number which is a mandatory field.  
If our shopping cart doesn't need User's Phone Number as mandatory Field then we can register automatically without showing the Registration Form to the User.  I will try to make this(User's Phone Number as Mandatory or not) as configurable during Installation (in the gocart.php).

<i>"What would happen if I were to log in with google or open ID and change my password in GoCart?"</i>
Sorry I didn't get this question clearly, could you please elaborate.
Currently when a user Logged-in using Google or Yahoo for the first time, we create a dummy password for him.  If he wants to directly login with GoCart in the future, he can set a password in MyAccounts page or click forgot password. 

#### My main goal behind social login is that the User doesn't need to remember one more password.

I am also working on few more Issues(Enhancement).

Please have a look at them here
https://github.com/IndianECommerceDevelopers/GoCart/issues?sort=created&direction=desc&state=open
Let me know your opinion.
If any issue is of interest for you I will take them on priority.  Also let me know if any issue is already implemented.

**Comment by gocart** [comment]
Ok, you answered my question appropriately even though you didn't understand it clearly.

There is no real reason to require a phone number, unless the customer (who owns the cart) wants a phone number. I'm still interested in this feature, but I'm not sure that I'm ready to include it as a core feature.

I may need to build a wiki for the gocartdv.com website where features like this can be added for those who are interested, but not necessarily part of the base system. I will think on this for a bit and get back with you.

thanks so much again for your interest in the system I will review your other issues and see if anything jumps out at me.

**Comment by Dinesh-Ramakrishnan** [comment]
Hi,
Is it possible to have another package called GoCart+ in which we can include such extra features?
Also we can always tag the GoCart+ as in alpha or beta stage and get the User's feedback on which feature of GoCart+ they like to have ported back to our Meanstream GoCart.
Thank you 
Regards,
Dinesh

**Pull request closed without merging**
