### PR TITLE
Moved all config_item('admin_folder') in replace of ADMIN_AREA constant

### PR DESCRIPTION
**Pull request by og-shawn-crigger**
Removed config_item('admiin_folder') and replaced with a CONSTANT,  I find that it is shorter and faster to access a constant then a value stored in a config file, even if cached.  

Not sure if this pull request is useful or not but figured I would offer my changes, and thank you for the cart software really shaping up

### CODE REVIEW

**Comment by og-shawn-crigger** [comment]
Just a note on this commit,  I personally like having my Admin area names either in a CONSTANT which I always believed would be the fastest method but could be wrong on benchmarks I have never tested the speed or anything of this.

It was just something I added my fork and figured it might help you out if you like it,  I also left the start of some development tools I add to my forks that might come in handy,  we use a lot of the tools on the CI-Bonfire project and my tools have evolved from there

**Comment by gocart** [comment]
I'll have to revisit this at a later time. Currently I cannot automatically merge this request. I am interested in your developer tools too. Could you elaborate on what they do?

**Comment by og-shawn-crigger** [comment]
The developer tools, I'll have to revisit to explain them better, but there basically the profiler bar from CI-Bonfire that I'm a developer of, and I just add them into all my sites it makes life a lot easier,  not sure which version was in the pull request atm. 

## 

Suppport at S-Vizion
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by og-shawn-crigger** [comment]
Ok on my Developer tools, I use a Console Logger, Chrome Logger and a JavaScript CI Profiler bar that makes it easy to debug what is going on

Lonnie Ezell's old profiler bar 

https://github.com/lonnieezell/codeigniter-forensics

ChromePHP Logger

http://marcomonteiro.net/wp/blog/2012/05/21/chromephp-and-codeigniter/

The rest is just a few helpers and stuff to make life easier like adding a logit method that logs the message with Ci, and thru the Console profiler bars and stuff if that makes sense at all.

**Pull request closed without merging**
