### PR TITLE
Bootswatch based Twitter Bootstrap Themes

### PR DESCRIPTION
**Pull request by Dinesh-Ramakrishnan**
Option to select one of the Bootswatch(http://bootswatch.com/) Themes for Twitter Bootstrap.

### CODE REVIEW

**Comment by gocart** [comment]
Hey dinesh. I don't think that this should be included by default, because it assumes that everyone will just stick with bootstrap. But, I do think it's a really cool idea. I'm currently working on a private copy of GoCart that will support addons, and it would be interesting to see something like this developed into a theme/addon for GoCart.

**Comment by olimortimer** [comment]
Definitely a good idea.  It would be great to see more GoCart add-ons / modules.  Maybe using something like CodeIgniter Sparks?

**Comment by Dinesh-Ramakrishnan** [comment]
sure, I will wait for the addons.  I have also developed some modules to support Social Login (Login via Facebook, Google, Yahoo, twitter, etc., ) (https://github.com/IndianECommerceDevelopers/GoCart) but couldn't get it pushed into the main GoCart since it is out of its scope.  If we have addons then I can add the Social Login as an addon too.

**Comment by Dinesh-Ramakrishnan** [comment]
any update on this.

**Pull request closed without merging**
