### PR TITLE
Dynamic Routing

### PR DESCRIPTION
**Pull request by pro1**
Changed the way dynamic routing was being handled, switched to a cached routes method which no longer requires a db query on every page request and utilizes the CI DB drivers.

Benefits performance and supports multiple database drivers.

### CODE REVIEW

**Comment by gocart** [comment]
Hey there, Your pull-request got me thinking a little bit on this. Originally GoCart had a route mapping system that modified the routes table and it worked, but was sort of janky and was difficult to fix if something were to get screwed up. One big strength of it is that it scaled better than the current method.

I'm thinking that either way we do it now, whether it's a database call at launch or a database call that generates a static file on save (of a route related item) either way we face a potential problem with a large database. Essentially if someone has 1000 products we're going to hit a resource wall.

I'm thinking now that perhaps a modification of the core routing file is a better option. For instance we allow CodeIgniter to do it's thing and check directories controllers etc. then the routes file and after this we add in an extra check. If the route doesn't naturally exist in file names, or in the routes directory then we do a sql query for only the route we're needing. It would still result in a database call for each product/category call etc. but it would be a much smaller result, and would allow the cart to scale to thousands of products without bottle necking.

I'd like to get your thoughts on this before implementing it.

**Comment by pro1** [comment]
I have extended the Router class in the past for personalised user URLs, it's easy to implement and works well but still requires a query to the database for every page request that does not match a system route.

I did some benchmarks with 1,000 routes with the cached solution and it executes on average in 1.7 seconds with a minimal increase on memory usage. Problems will occur if a cart approaches the 10,000 route mark which execute on average in 83 seconds.

I did not benchmark any increments between 1,000 and 10,000 but I could if you're interested.

**Comment by pro1** [comment]
I should clarify, the increase in execution times is only while saving the cached routes file, I did not benchmark front end pages.

**Comment by gocart** [comment]
Hey there, I am working on a private copy of the GoCart code right now. I implemented the modified route library and it works pretty good. It also now supports the ability to string together multiple slugs (only looking at the last two in order to build a URL based breadcrumb trail. I think as far as long term goes, that's the best way to go. I have been thinking though that in that routes file, when a route is discovered it could write that route to a cached route file like your solution, but only on a per find basis. If a product is updated, the cache file can be deleted and started over. I probably won't implement this feature right away because of all the other things I need to work on, but I believe it would be a good mix of the various methods we've discussed here.

**Pull request closed without merging**
